export default appContent = [
    {
        id: 1,
        title: "Ashram",
        teaser: "Cruise Control!!!",
        description:
            "Unforeseen Incidents is a classical style interactive mystery set in a beautifully hand-painted world. Join Harper Pendrell and experience a challenging investigation, smart dialog and a rich cast of characters in this thrilling new adventure game.",
        rating: 4.5,
        category: ["1-3KM Pins",
        "3-5KM Pins",
        "5-10KM Pins"],
        age: "12+",
        createdAt: "5",
        profile:require("./assets/user1/profile.jpg"),
        cover: require("./assets/user1/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            // require("./assets/unforeseen_2.jpg"),
            // require("./assets/unforeseen_3.jpg"),
            // require("./assets/unforeseen_4.jpg"),
            // require("./assets/unforeseen_5.jpg"),
            // require("./assets/unforeseen_6.jpg"),
        ],
        backgroundColor: "#824571",
    },
    {
        id: 2,
        title: "Ronnie",
        teaser: "I hope Drake is okay.",
        description:
            "Play the critically acclaimed masterpiece. Embark on a new journey in a vast, exotic world where you’ll encounter towering enemies and challenging puzzles on your quest to unravel Ori’s destiny.",
        rating: 3.8,
        category: ["3-5KM Pins",
        "5-10KM Pins",
        "10-20KM Pins"],
        age: "11+",
        createdAt: "11",
        profile:require("./assets/user2/profile.jpg"),
        cover: require("./assets/user2/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#456382",
    },
    {
        id: 3,
        title: "Lena",
        teaser: "He's definitely having a great time ",
        description:
            "Unravel is a physics-based puzzle platformer. Yarny, a character made from a single thread of yarn, must embark on a larger than life adventure.",
        rating: 2.4,
        category: ["5-10KM Pins",
        "10-20KM Pins",
        "20-50KM Pins"],
        age: "13+",
        createdAt: "18",
        profile:require("./assets/user3/profile.jpg"),
        cover: require("./assets/user3/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#825D45",
    },
    {
        id: 4,
        title: "Terry",
        teaser: "I love it here! ",
        description:
            "Unravel is a physics-based puzzle platformer. Yarny, a character made from a single thread of yarn, must embark on a larger than life adventure.",
        rating: 2.4,
        category: ["5-10KM Pins",
        "10-20KM Pins",
        "20-50KM Pins"],
        age: "13+",
        createdAt: "21",
        profile:require("./assets/user4/profile.jpg"),
        cover: require("./assets/user4/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#825D45",
    },
    {
        id: 5,
        title: "Micheal",
        teaser: "When theres no milk in the fridge ",
        description:
            "Unravel is a physics-based puzzle platformer. Yarny, a character made from a single thread of yarn, must embark on a larger than life adventure.",
        rating: 2.4,
        category: ["5-10KM Pins",
        "10-20KM Pins",
        "20-50KM Pins"],
        age: "13+",
        createdAt: "25",
        profile:require("./assets/user5/profile.jpg"),
        cover: require("./assets/user5/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#825D45",
    },
    {
        id: 6,
        title: "Complex",
        teaser: "Alicia Keys new album is out now ",
        description:
            "Unravel is a physics-based puzzle platformer. Yarny, a character made from a single thread of yarn, must embark on a larger than life adventure.",
        rating: 2.4,
        category: ["5-10KM Pins",
        "10-20KM Pins",
        "20-50KM Pins"],
        age: "13+",
        createdAt: "34",
        profile:require("./assets/user6/profile.jpg"),
        cover: require("./assets/user6/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#825D45",
    },
    {
        id: 7,
        title: "Alicia",
        teaser: "I heard its the weekend",
        description:
            "Unravel is a physics-based puzzle platformer. Yarny, a character made from a single thread of yarn, must embark on a larger than life adventure.",
        rating: 2.4,
        category: ["5-10KM Pins",
        "10-20KM Pins",
        "20-50KM Pins"],
        age: "13+",
        createdAt: "34",
        profile:require("./assets/user7/profile.jpg"),
        cover: require("./assets/user7/pic.jpg"),
        screenshots: [
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
            require("./assets/avatar.png"),
        ],
        backgroundColor: "#825D45",
    },
];
